### ISSUE TITLE
Terraform apply fails when there is none default terraform binary path

### ISSUE THREAD

**Issue by apielasa** [StackStorm-Exchange/stackstorm-terraform#40]
Terraform apply action fails in case of setting none default terraform_exec parameter.

error message:
 No such file or directory: 'terraform'\n",

The root cause of this problem is self.set_semantic_version(), which is run before terraform_bin_path is assigned.

In this case, set_semantic_version tries to use the default value, which doesn't work.

Please find my PR that solves this problem

https://github.com/StackStorm-Exchange/stackstorm-terraform/pull/39/files

**Comment by martezr** [comment]
It looks like this issue has been resolved as the associated PR (#39)has been merged.

**Comment by arm4b** [comment]
Thanks, @martezr, closing!
