### ISSUE TITLE
Missing auto-approve?

### ISSUE THREAD

**Issue by mjtice** [StackStorm-Exchange/stackstorm-terraform#5]
Maybe I'm missing something documented - but when I try to run an `apply` action st2 fails with:

`Error: Apply cancelled.`  Presumably because the binary is waiting for confirmation to apply the plan.

If I update apply.py (line 20) with `return_code, stdout, stderr = self.terraform.apply(plan_path, var_file=variable_files, auto_approve=True)` it works as expected.

**Comment by arm4b** [comment]
Can you provide a PR with a code change to fix that?
